addons:
  firefox: "49.0"
sudo: required
language: c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xvfb
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/johnelse/ocaml-webtest/master/test/setup_geckodriver.sh
  - bash -ex setup_geckodriver.sh
  - sudo -H pip install selenium==3.0.1
    # These links are needed to allow the dependency tests to run. Remove once
    # travis scripts don't run dependency tests.
  - sudo ln -sf $HOME/firefox-50.0/firefox/firefox /usr/local/bin/firefox
  - sudo ln -sf $HOME/firefox-50.0/firefox/firefox-bin /usr/local/bin/firefox-bin
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=promise-js
    - EXTRA_REMOTES=git://github.com/johnelse/opam-repo-johnelse
  matrix:
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
